dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.1

compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1'

dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}
  from_key_2: ${PRIVATE_KEY_2}
  from_key_3: ${PRIVATE_KEY_3}
  from_key_4: ${PRIVATE_KEY_4}