dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.1

compiler:
  solc:
    version: 0.8.8
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1'

dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}
  from_key_2: ${PRIVATE_KEY_2}
  from_key_3: ${PRIVATE_KEY_3}
  from_key_4: ${PRIVATE_KEY_4}
  from_key_5: ${PRIVATE_KEY_5}

networks:
  binance-testnet:
    pancakeswap_router: '0x9Ac64Cc6e4415144C455BD8E4837Fea55603e5c3'
  bsc-test:
    pancakeswap_router: '0x9Ac64Cc6e4415144C455BD8E4837Fea55603e5c3'
  bsc-main:
    pancakeswap_router: '0x10ED43C718714eb63d5aA57B78B54704E256024E'
  rinkeby:
    pancakeswap_router: '0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D'